server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://db_cw:5432/javaCW
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.office365.com
    port: 587
    username: sharaga1937@outlook.com
    password: there_is_no_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:

    user:
      name: admin
      password: password
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  token:
    validity-time: ${JWT_TOKEN_VALIDITY:86400000} # 24 hours
